### ISSUE TITLE
curl against nodePort hangs after enabling eBPF

### ISSUE THREAD

**Issue by marcindulak** [tigera/ccol1#3]
Course > Week 4 > Understanding Calico Native Service Handling > Source IP preservation

`curl 198.19.0.1:30180` hangs.

Using https://docs.projectcalico.org/archive/v3.16/manifests/tigera-operator.yaml

Reported on #academy slack on September 16 2021.

**Comment by cdtomkins** [comment]
Thanks - acknowledged. As discussed I intend to work to move the course to a newer Calico version soon - no ETA is set for this yet but I am hopeful of probably picking it up early next month.

**Comment by cdtomkins** [comment]
Thanks for raising this, @marcindulak. I have just switched the CCO-L1 course to use v3.19 instead. I then went through the entire CCO-L1 course and confirmed that it fixed the issue and also has not caused any regressions elsewhere. All looks good.
